### ISSUE TITLE
How to use the pre-trained embedding, e.g. twitter_wiki_germeval_1000.bin? And the window size of the CNN in paper?

### ISSUE THREAD

**Issue by jingliao132** [UKPLab/germeval2017-sentiment-detection#1]
Hello, UKPLab. I have download the pre-trained embeddings in binary format. How could it be made into an embedding vector based on certain vocabulary?  Do you provide any interface like  **gensim**? 

Besides, I failed to find setup of CNN window size but the _CNN-non-static_  in (Kim, 2014) work that you refer to suggest the window size should be defined. Is the tweet length fixed in input? If so, what is the window size value?

In general, I am not quite clear about how you preprocessing original tweets, could you please describe or recommend any resources about initializing embeddings for tweets?

Thanks a lot.

**Comment by Wuhn** [comment]
Hi @jingliao132 ,

[sent2vec](https://github.com/epfml/sent2vec#train-a-new-sent2vec-model) already provides an interface to use the embeddings:
```
import sent2vec
model = sent2vec.Sent2vecModel()
model.load_model('model.bin')
emb = model.embed_sentence("once upon a time .") 
embs = model.embed_sentences(["first sentence .", "another sentence"])
```
You can then use the resulting embedding vectors in any way (e.g., as input for a sentence classifier). 

Regarding the window size: 
Sent2vec uses dynamic context windows as described in the [paper](https://www.aclweb.org/anthology/N18-1049.pdf). If the question is wrt. the n-gram size, we use the default value (2). 

Sorry for the late reply, we hope you were still able to resolve the issues.

Best,
Ji-Ung

**Comment by jingliao132** [comment]
Thanks for your help. My issues are well-resolved. 

Best regards,
Jing
